const express = require('express');
const app = express();
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');
console.log('Hello JavaScript');

app.listen(8080);
console.log('---Server Started at port 8080');